const datiDistro = [
  {
    id: 1,
    name: "Ubuntu",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 22.04,
    rating: 5.5,
    punti: 23,
    hero: false,
    image:
      "https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_720/https://lh6.googleusercontent.com/hudiV1JElIOeNNSTcnVRLCQ-Ekr_COZepxM_UBWmBZyDUeP3wzE9cGUyB8zZMNPiyQQXkmEmOssKNvs1VMvx58N5ayB6e8-eaiU0wHrr76_QdiD7M-vvbtce2LYJ6LsyS9YUGs2T",
    base: "Debian",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Logo-ubuntu_cof-orange-hex.svg/1200px-Logo-ubuntu_cof-orange-hex.svg.png",
    website: "https://ubuntu.com",
  },
  {
    id: 2,
    name: "Manjaro",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 22.1,
    rating: 4,
    punti: 21,
    hero: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Manjaro_20.2_screenshot.png/1200px-Manjaro_20.2_screenshot.png",
    base: "Arch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Manjaro-logo.svg/512px-Manjaro-logo.svg.png?20210414143234",
    website: "https://manjaro.org",
  },
  {
    id: 3,
    name: "Parrot OS",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 5.3,
    rating: 8,
    punti: 52,
    hero: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/ParrotOS-4.6-plasma.jpg/1200px-ParrotOS-4.6-plasma.jpg",
    base: "Debian",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Parrot_Logo.png",
    website: "https://www.parrotsec.org",
  },
  {
    id: 4,
    name: "Mint",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 21.1,
    rating: 6.5,
    punti: 33,
    hero: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Linux_Mint_20.3_%28Una%29_Cinnamon.png/1200px-Linux_Mint_20.3_%28Una%29_Cinnamon.png",
    base: "Debian",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Linux_Mint_logo_without_wordmark.svg/1200px-Linux_Mint_logo_without_wordmark.svg.png",
    website: "https://linuxmint.com",
  },
  {
    id: 5,
    name: "EndeavourOS",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 22.12,
    rating: 8.5,
    punti: 60,
    hero: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/4d/EndeavourOS_21.4_screenshot.png",
    base: "Arch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/EndeavourOS_Logo.svg/1200px-EndeavourOS_Logo.svg.png",
    website: "https://endeavouros.com",
  },
  {
    id: 6,
    name: "Fedora",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 38,
    rating: 6.5,
    punti: 35,
    hero: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/98/Fedora_Workstation_37_%28November_2022%29_—_default_desktop_environment.png",
    base: "Arch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Fedora_logo.svg/2048px-Fedora_logo.svg.png",
    website: "https://fedoraproject.org",
  },
  {
    id: 7,
    name: "Pop!_OS",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium corporis impedit omnis ratione",
    version: 22.04,
    rating: 9,
    punti: 68,
    hero: false,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Apps_Pop%21_OS_21.10.png/1200px-Apps_Pop%21_OS_21.10.png",
    base: "Debian",
    logo: "https://i0.wp.com/cupofmoe.com/wp-content/uploads/2017/02/System76-Logo.png?fit=768%2C768&ssl=1",
    website: "https://pop.system76.com",
  },
];

export default datiDistro;
